### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [sugarso/WWDC#55]
Hi,

Please add setup instructions to the readme. Running `pod install` shows the following message.

**CocoaPods-Keys has detected a keys mismatch for your setup.
 What is the key for GoogleAnalytics**

**Comment by genadyo** [comment]
The keys for the services are not stored here, you can create your own accounts or disable them.

**Comment by Isuru-Nanayakkara** [comment]
How do I disable them?

**Comment by genadyo** [comment]
Just use some random string there.
