### ISSUE TITLE
Mark newly added parties

### ISSUE THREAD

**Issue by khanov** [sugarso/WWDC#57]
Hi! I have been using the app since WWDC 2014 and it's the best app for tracking WWDC parties. Here's a little nice feature suggestion.

Currently, it's hard to find new parties added. I think it would be much easier for returning users if the app somehow highlighted new parties in the list, like below:

![iphone 6 plus 1x - portrait](https://cloud.githubusercontent.com/assets/869923/7567588/6975e518-f817-11e4-8a94-7daede942709.png)

This little label 'New' makes it much easier to quickly scroll through the list and see if there are any new parties.

Thanks!

**Comment by genadyo** [comment]
Good idea!

**Comment by genadyo** [comment]
![screen shot 2015-05-22 at 02 21 06](https://cloud.githubusercontent.com/assets/2101043/7760970/34de0474-0029-11e5-8e11-d2942fbd564e.png)
