### ISSUE TITLE
Going to an event button

### ISSUE THREAD

**Issue by gabac** [sugarso/WWDC#58]
Would'nt it make more sense to rename the button "Not Going" to "Going" and color it green after the user has pressed it?
It wasn't that obvious to me that I should press "Not going" to add an event to my list of parties I'm going to.

**Comment by genadyo** [comment]
![screen recording 2015-05-21 at 23-38](https://cloud.githubusercontent.com/assets/2101043/7758442/6e61ec0e-0012-11e5-9473-110f319bd842.gif)

**Comment by genadyo** [comment]
![screen recording 2015-05-22 at 00-47](https://cloud.githubusercontent.com/assets/2101043/7759673/29255dba-001c-11e5-8e8a-cad0914c620f.gif)
